# Round settings
title = "Chiron Round 1"

# Image settings
user = "cpadmin"
os = "Ubuntu 20.04"

# Remote settings
remote = "https://google.com"
local = true

[[check]]
name = "Firewall is enabled"
points = 10

	[[check.pass]]
	# all *contains checks are regex by default
	type = "CommandContains"
	command = "echo hello world"
	contains = "^hello[[:space:]]world"

[[check]]
name = "Auditd has been installed"
points = 10

	[[check.pass]]
	type = "PackageInstalled"
	package = "auditd"

[[check]]
name = "Fixed permissions for /etc/passwd"
points = 10

	[[check.pass]]
	type = "FilePermissions"
	file = "/etc/passwd"
	perms = 644
