name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions-rs/toolchain@v1
      - run: sudo apt install -y libdpkg-dev
      - uses: actions/checkout@v2
        with:
          toolchain: stable
      - name: Build
        run: cargo build
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set up
        uses: actions-rs/toolchain@v1
      - uses: actions/checkout@v2
        with:
          toolchain: stable
      - name: Build
        run: cargo build
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt -- --check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - run: sudo apt install -y libdpkg-dev
      - uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy -- -D warnings
